var shadow$provide = {};
(function(root, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory);
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.returnExports = factory();
  }
})(this, function() {
  var shadow$umd$export = null;
'use strict';var g;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function r(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a){const b=[];let c=0;for(const d in a)b[c++]=d;return b};function da(a,b){null!=a&&this.append.apply(this,arguments)}g=da.prototype;g.Ba="";g.set=function(a){this.Ba=""+a};g.append=function(a,b,c){this.Ba+=String(a);if(null!=b)for(let d=1;d<arguments.length;d++)this.Ba+=arguments[d];return this};g.clear=function(){this.Ba=""};g.toString=function(){return this.Ba};var u={},fa=null;function ha(){return new ia(null,5,[ja,!0,ka,!0,la,!1,na,!1,oa,null],null)}function v(a){return null!=a&&!1!==a}function w(a,b){return a[r(null==b?null:b)]?!0:a._?!0:!1}function x(a,b){var c=null==b?null:b.constructor;return Error(["No protocol method ",a," defined for type ",v(v(c)?c.Mb:c)?c.ob:r(b),": ",b].join(""))}function pa(a){var b=a.ob;return v(b)?b:z.g(a)}var qa="undefined"!==typeof Symbol&&"function"===r(Symbol)?Symbol.iterator:"@@iterator";
function B(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}function ra(){}function sa(a){if(null!=a&&null!=a.V)a=a.V(a);else{var b=sa[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=sa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ICounted.-count",a);}return a}function ta(){}
function ua(a){if(null!=a&&null!=a.W)a=a.W(a);else{var b=ua[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ua._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IEmptyableCollection.-empty",a);}return a}function va(){}function wa(a,b){if(null!=a&&null!=a.U)a=a.U(a,b);else{var c=wa[r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=wa._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("ICollection.-conj",a);}return a}function xa(){}
var ya=function(){function a(d,e,f){var h=D[r(null==d?null:d)];if(null!=h)return h.l?h.l(d,e,f):h.call(null,d,e,f);h=D._;if(null!=h)return h.l?h.l(d,e,f):h.call(null,d,e,f);throw x("IIndexed.-nth",d);}function b(d,e){var f=D[r(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=D._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw x("IIndexed.-nth",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.l=a;return c}(),D=function D(a){switch(arguments.length){case 2:return D.h(arguments[0],arguments[1]);case 3:return D.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};D.h=function(a,b){return null!=a&&null!=a.T?a.T(a,b):ya(a,b)};D.l=function(a,b,c){return null!=a&&null!=a.la?a.la(a,b,c):ya(a,b,c)};D.Y=3;
function E(a){if(null!=a&&null!=a.ca)a=a.ca(a);else{var b=E[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=E._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ISeq.-first",a);}return a}function G(a){if(null!=a&&null!=a.ga)a=a.ga(a);else{var b=G[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=G._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ISeq.-rest",a);}return a}function za(){}function Aa(){}
var Ca=function(){function a(d,e,f){var h=Ba[r(null==d?null:d)];if(null!=h)return h.l?h.l(d,e,f):h.call(null,d,e,f);h=Ba._;if(null!=h)return h.l?h.l(d,e,f):h.call(null,d,e,f);throw x("ILookup.-lookup",d);}function b(d,e){var f=Ba[r(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=Ba._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw x("ILookup.-lookup",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.l=a;return c}(),Ba=function Ba(a){switch(arguments.length){case 2:return Ba.h(arguments[0],arguments[1]);case 3:return Ba.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};Ba.h=function(a,b){return null!=a&&null!=a.ka?a.ka(a,b):Ca(a,b)};Ba.l=function(a,b,c){return null!=a&&null!=a.H?a.H(a,b,c):Ca(a,b,c)};Ba.Y=3;function Da(){}
function Ea(a,b){if(null!=a&&null!=a.Ua)a=a.Ua(a,b);else{var c=Ea[r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Ea._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IAssociative.-contains-key?",a);}return a}function Fa(a,b,c){if(null!=a&&null!=a.xa)a=a.xa(a,b,c);else{var d=Fa[r(null==a?null:a)];if(null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=Fa._,null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw x("IAssociative.-assoc",a);}return a}function Ga(){}
function Ha(a){if(null!=a&&null!=a.Fb)a=a.key;else{var b=Ha[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ha._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IMapEntry.-key",a);}return a}function Ia(a){if(null!=a&&null!=a.Gb)a=a.G;else{var b=Ia[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ia._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IMapEntry.-val",a);}return a}function Ja(){}
function Ka(a){if(null!=a&&null!=a.zb)a=a.G;else{var b=Ka[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ka._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IDeref.-deref",a);}return a}function La(){}function Ma(a){if(null!=a&&null!=a.P)a=a.P(a);else{var b=Ma[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ma._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IMeta.-meta",a);}return a}
function Na(a,b){if(null!=a&&null!=a.R)a=a.R(a,b);else{var c=Na[r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Na._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IWithMeta.-with-meta",a);}return a}function Oa(){}
var Qa=function(){function a(d,e,f){var h=Pa[r(null==d?null:d)];if(null!=h)return h.l?h.l(d,e,f):h.call(null,d,e,f);h=Pa._;if(null!=h)return h.l?h.l(d,e,f):h.call(null,d,e,f);throw x("IReduce.-reduce",d);}function b(d,e){var f=Pa[r(null==d?null:d)];if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);f=Pa._;if(null!=f)return f.h?f.h(d,e):f.call(null,d,e);throw x("IReduce.-reduce",d);}var c=null;c=function(d,e,f){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,f)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.l=a;return c}(),Pa=function Pa(a){switch(arguments.length){case 2:return Pa.h(arguments[0],arguments[1]);case 3:return Pa.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};Pa.h=function(a,b){return null!=a&&null!=a.aa?a.aa(a,b):Qa(a,b)};Pa.l=function(a,b,c){return null!=a&&null!=a.ba?a.ba(a,b,c):Qa(a,b,c)};Pa.Y=3;function Ra(){}
function Sa(a,b){if(null!=a&&null!=a.hb)a=a.hb(a,b,!0);else{var c=Sa[r(null==a?null:a)];if(null!=c)a=c.l?c.l(a,b,!0):c.call(null,a,b,!0);else if(c=Sa._,null!=c)a=c.l?c.l(a,b,!0):c.call(null,a,b,!0);else throw x("IKVReduce.-kv-reduce",a);}return a}function Ta(a,b){if(null!=a&&null!=a.K)a=a.K(a,b);else{var c=Ta[r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Ta._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IEquiv.-equiv",a);}return a}
function Ua(a){if(null!=a&&null!=a.O)a=a.O(a);else{var b=Ua[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ua._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IHash.-hash",a);}return a}function Va(){}function Wa(a){if(null!=a&&null!=a.I)a=a.I(a);else{var b=Wa[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Wa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ISeqable.-seq",a);}return a}function Xa(){}function Ya(){}function Za(){}
function H(a,b){if(null!=a&&null!=a.ub)a=a.ub(a,b);else{var c=H[r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=H._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("IWriter.-write",a);}return a}function $a(){}function ab(a,b,c){if(null!=a&&null!=a.M)a=a.M(a,b,c);else{var d=ab[r(null==a?null:a)];if(null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=ab._,null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw x("IPrintWithWriter.-pr-writer",a);}return a}
function bb(a){if(null!=a&&null!=a.Xa)a=a.Xa(a);else{var b=bb[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=bb._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IEditableCollection.-as-transient",a);}return a}function cb(a,b){if(null!=a&&null!=a.$a)a=a.$a(a,b);else{var c=cb[r(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=cb._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw x("ITransientCollection.-conj!",a);}return a}
function db(a){if(null!=a&&null!=a.ib)a=a.ib(a);else{var b=db[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=db._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("ITransientCollection.-persistent!",a);}return a}function eb(a,b,c){if(null!=a&&null!=a.Va)a=a.Va(a,b,c);else{var d=eb[r(null==a?null:a)];if(null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=eb._,null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw x("ITransientAssociative.-assoc!",a);}return a}
function fb(a){if(null!=a&&null!=a.qb)a=a.qb(a);else{var b=fb[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=fb._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IChunk.-drop-first",a);}return a}function gb(a){if(null!=a&&null!=a.mb)a=a.mb(a);else{var b=gb[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=gb._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IChunkedSeq.-chunked-first",a);}return a}
function hb(a){if(null!=a&&null!=a.gb)a=a.gb(a);else{var b=hb[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=hb._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IChunkedSeq.-chunked-rest",a);}return a}function ib(){}function jb(a){if(null!=a&&null!=a.sa)a=a.sa(a);else{var b=jb[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=jb._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IIterable.-iterator",a);}return a}
function kb(a){this.Ob=a;this.j=1073741824;this.A=0}kb.prototype.ub=function(a,b){return this.Ob.append(b)};function lb(a){var b=new da;a.M(null,new kb(b),ha());return z.g(b)}var mb="undefined"!==typeof Math&&"undefined"!==typeof Math.imul?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function nb(a){a=mb(a|0,-862048943);return mb(a<<15|a>>>-15,461845907)}
function ob(a,b){a=(a|0)^(b|0);return mb(a<<13|a>>>-13,5)+-430675100|0}function pb(a,b){a=(a|0)^b;a=mb(a^a>>>16,-2048144789);a=mb(a^a>>>13,-1028477387);return a^a>>>16}function qb(a){a:{var b=1;for(var c=0;;)if(b<a.length)c=ob(c,nb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16)),b+=2;else{b=c;break a}}return pb(1===(a.length&1)?b^nb(a.charCodeAt(a.length-1)):b,mb(2,a.length))}var rb={},sb=0;
function tb(a){255<sb&&(rb={},sb=0);if(null==a)return 0;var b=rb[a];if("number"===typeof b)a=b;else{a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)d=mb(31,d)+a.charCodeAt(c),c+=1;else{b=d;break a}else b=0;else b=0;rb[a]=b;sb+=1;a=b}return a}
function ub(a){if(null!=a&&(a.j&4194304||u===a.Tb))return a.O(null)^0;if("number"===typeof a){if(isFinite(a))return Math.floor(a)%2147483647;switch(a){case Infinity:return 2146435072;case -Infinity:return-1048576;default:return 2146959360}}else return!0===a?a=1231:!1===a?a=1237:"string"===typeof a?(a=tb(a),a=0===a?a:pb(ob(0,nb(a)),4)):a=a instanceof Date?a.valueOf()^0:null==a?0:Ua(a)^0,a}function vb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}
function wb(a,b,c,d,e){this.fb=a;this.name=b;this.Aa=c;this.Ta=d;this.ra=e;this.j=2154168321;this.A=4096}g=wb.prototype;g.toString=function(){return this.Aa};g.K=function(a,b){return b instanceof wb?this.Aa===b.Aa:!1};g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};
g.g=function(a){return xb.h?xb.h(a,this):xb.call(null,a,this)};g.h=function(a,b){return xb.l?xb.l(a,this,b):xb.call(null,a,this,b)};g.P=function(){return this.ra};g.R=function(a,b){return new wb(this.fb,this.name,this.Aa,this.Ta,b)};g.O=function(){var a=this.Ta;return null!=a?a:this.Ta=a=vb(qb(this.name),tb(this.fb))};g.M=function(a,b){return H(b,this.Aa)};
var yb=function yb(a){switch(arguments.length){case 1:return yb.g(arguments[0]);case 2:return yb.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};yb.g=function(a){for(;;){if(a instanceof wb)return a;if("string"===typeof a){var b=a.indexOf("/");return 1>b?yb.h(null,a):yb.h(a.substring(0,b),a.substring(b+1,a.length))}if(a instanceof I)a=a.va;else throw Error("no conversion to symbol");}};
yb.h=function(a,b){var c=null!=a?[z.g(a),"/",z.g(b)].join(""):b;return new wb(a,b,c,null,null)};yb.Y=2;function zb(a){return null!=a?a.A&131072||u===a.Ub?!0:a.A?!1:w(ib,a):w(ib,a)}
function K(a){if(null==a)return null;if(null!=a&&(a.j&8388608||u===a.Kb))return a.I(null);if(Array.isArray(a)||"string"===typeof a)return 0===a.length?null:new M(a,0,null);if(null!=a&&null!=a[qa])return a=(null!==a&&qa in a?a[qa]:void 0).call(a),Ab.g?Ab.g(a):Ab.call(null,a);if(w(Va,a))return Wa(a);throw Error([z.g(a)," is not ISeqable"].join(""));}function N(a){if(null==a)return null;if(null!=a&&(a.j&64||u===a.Za))return a.ca(null);a=K(a);return null==a?null:E(a)}
function Bb(a){return null!=a?null!=a&&(a.j&64||u===a.Za)?a.ga(null):(a=K(a))?a.ga(null):O:O}function P(a){return null==a?null:null!=a&&(a.j&128||u===a.Ya)?a.Z():K(Bb(a))}var R=function R(a){switch(arguments.length){case 1:return R.g(arguments[0]);case 2:return R.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return R.J(arguments[0],arguments[1],new M(c.slice(2),0,null))}};R.g=function(){return!0};
R.h=function(a,b){return null==a?null==b:a===b||Ta(a,b)};R.J=function(a,b,c){for(;;)if(R.h(a,b))if(P(c))a=b,b=N(c),c=P(c);else return R.h(b,N(c));else return!1};R.X=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return this.J(b,a,c)};R.Y=2;function Cb(a){this.C=a}Cb.prototype.next=function(){if(null!=this.C){var a=N(this.C);this.C=P(this.C);return{value:a,done:!1}}return{value:null,done:!0}};function Db(a){return new Cb(K(a))}
function Eb(a,b){this.value=a;this.vb=b;this.jb=null;this.j=8388672;this.A=0}Eb.prototype.I=function(){return this};Eb.prototype.ca=function(){return this.value};Eb.prototype.ga=function(){null==this.jb&&(this.jb=Ab.g?Ab.g(this.vb):Ab.call(null,this.vb));return this.jb};function Ab(a){var b=a.next();return v(b.done)?null:new Eb(b.value,a)}function Fb(a){var b=0,c=1;for(a=K(a);;)if(null!=a)b+=1,c=mb(31,c)+ub(N(a))|0,a=P(a);else return pb(ob(0,nb(c)),b)}var Gb=pb(ob(0,nb(1)),0);
function Hb(a){var b=0,c=0;for(a=K(a);;)if(null!=a)b+=1,c=c+ub(N(a))|0,a=P(a);else return pb(ob(0,nb(c)),b)}var Ib=pb(ob(0,nb(0)),0);ra["null"]=!0;sa["null"]=function(){return 0};Date.prototype.K=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Ta.number=function(a,b){return a===b};La["function"]=!0;Ma["function"]=function(){return null};Ua._=function(a){return Object.prototype.hasOwnProperty.call(a,aa)&&a[aa]||(a[aa]=++ba)};function Jb(){this.G=!1;this.j=32768;this.A=0}
Jb.prototype.zb=function(){return this.G};function Kb(a){return a instanceof Jb}function Lb(a){return Ka(a)}function Mb(a,b){var c=a.length;if(0===a.length)return b.F?b.F():b.call(null);for(var d=a[0],e=1;;)if(e<c){var f=a[e];d=b.h?b.h(d,f):b.call(null,d,f);if(Kb(d))return Ka(d);e+=1}else return d}function Nb(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var f=a[c];e=b.h?b.h(e,f):b.call(null,e,f);if(Kb(e))return Ka(e);c+=1}else return e}
function Ob(a,b,c,d){for(var e=a.length;;)if(d<e){var f=a[d];c=b.h?b.h(c,f):b.call(null,c,f);if(Kb(c))return Ka(c);d+=1}else return c}function Pb(a){return null!=a?a.j&2||u===a.yb?!0:a.j?!1:w(ra,a):w(ra,a)}function Qb(a){return null!=a?a.j&16||u===a.sb?!0:a.j?!1:w(xa,a):w(xa,a)}function S(a,b,c){var d=T.g?T.g(a):T.call(null,a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if(R.h(Rb?Rb(a,c):Sb.call(null,a,c),b))return c;c+=1}else return-1}
function U(a,b,c){var d=T.g?T.g(a):T.call(null,a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>c?d+c:c;for(;;)if(0<=c){if(R.h(Rb?Rb(a,c):Sb.call(null,a,c),b))return c;--c}else return-1}function Tb(a,b){this.i=a;this.o=b}Tb.prototype.ia=function(){return this.o<this.i.length};Tb.prototype.next=function(){var a=this.i[this.o];this.o+=1;return a};function M(a,b,c){this.i=a;this.o=b;this.u=c;this.j=166592766;this.A=139264}g=M.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T.g?T.g(this):T.call(null,this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.T=function(a,b){a=b+this.o;if(0<=a&&a<this.i.length)return this.i[a];throw Error("Index out of bounds");};g.la=function(a,b,c){a=b+this.o;return 0<=a&&a<this.i.length?this.i[a]:c};
g.sa=function(){return new Tb(this.i,this.o)};g.P=function(){return this.u};g.Z=function(){return this.o+1<this.i.length?new M(this.i,this.o+1,null):null};g.V=function(){var a=this.i.length-this.o;return 0>a?0:a};g.O=function(){return Fb(this)};g.K=function(a,b){return Ub.h?Ub.h(this,b):Ub.call(null,this,b)};g.W=function(){return O};g.aa=function(a,b){return Ob(this.i,b,this.i[this.o],this.o+1)};g.ba=function(a,b,c){return Ob(this.i,b,c,this.o)};g.ca=function(){return this.i[this.o]};
g.ga=function(){return this.o+1<this.i.length?new M(this.i,this.o+1,null):O};g.I=function(){return this.o<this.i.length?this:null};g.R=function(a,b){return b===this.u?this:new M(this.i,this.o,b)};g.U=function(a,b){return V.h?V.h(b,this):V.call(null,b,this)};M.prototype[qa]=function(){return Db(this)};function Vb(a){return 0<a.length?new M(a,0,null):null}Ta._=function(a,b){return a===b};
var Wb=function Wb(a){switch(arguments.length){case 0:return Wb.F();case 1:return Wb.g(arguments[0]);case 2:return Wb.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Wb.J(arguments[0],arguments[1],new M(c.slice(2),0,null))}};Wb.F=function(){return Xb};Wb.g=function(a){return a};Wb.h=function(a,b){return null!=a?wa(a,b):new Yb(null,b,null,1,null)};
Wb.J=function(a,b,c){for(;;)if(v(c))a=Wb.h(a,b),b=N(c),c=P(c);else return Wb.h(a,b)};Wb.X=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return this.J(b,a,c)};Wb.Y=2;function T(a){if(null!=a)if(null!=a&&(a.j&2||u===a.yb))a=a.V(null);else if(Array.isArray(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.j&8388608||u===a.Kb))a:{a=K(a);for(var b=0;;){if(Pb(a)){a=b+sa(a);break a}a=P(a);b+=1}}else a=sa(a);else a=0;return a}
function Zb(a,b,c){for(;;){if(null==a)return c;if(0===b)return K(a)?N(a):c;if(Qb(a))return D(a,b,c);if(K(a))a=P(a),--b;else return c}}function Sb(a){switch(arguments.length){case 2:return Rb(arguments[0],arguments[1]);case 3:return W(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}
function Rb(a,b){if("number"!==typeof b)throw Error("Index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.j&16||u===a.sb))return a.T(null,b);if(Array.isArray(a)){if(-1<b&&b<a.length)return a[b|0];throw Error("Index out of bounds");}if("string"===typeof a){if(-1<b&&b<a.length)return a.charAt(b|0);throw Error("Index out of bounds");}if(null!=a&&(a.j&64||u===a.Za)||null!=a&&(a.j&16777216||u===a.tb)){if(0>b)throw Error("Index out of bounds");a:for(;;){if(null==a)throw Error("Index out of bounds");
if(0===b){if(K(a)){a=N(a);break a}throw Error("Index out of bounds");}if(Qb(a)){a=D(a,b);break a}if(K(a))a=P(a),--b;else throw Error("Index out of bounds");}return a}if(w(xa,a))return D(a,b);throw Error(["nth not supported on this type ",z.g(pa(null==a?null:a.constructor))].join(""));}
function W(a,b,c){if("number"!==typeof b)throw Error("Index argument to nth must be a number.");if(null==a)return c;if(null!=a&&(a.j&16||u===a.sb))return a.la(null,b,c);if(Array.isArray(a))return-1<b&&b<a.length?a[b|0]:c;if("string"===typeof a)return-1<b&&b<a.length?a.charAt(b|0):c;if(null!=a&&(a.j&64||u===a.Za)||null!=a&&(a.j&16777216||u===a.tb))return 0>b?c:Zb(a,b,c);if(w(xa,a))return D(a,b,c);throw Error(["nth not supported on this type ",z.g(pa(null==a?null:a.constructor))].join(""));}
var xb=function xb(a){switch(arguments.length){case 2:return xb.h(arguments[0],arguments[1]);case 3:return xb.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};xb.h=function(a,b){return null==a?null:null!=a&&(a.j&256||u===a.Eb)?a.ka(null,b):Array.isArray(a)?null!=b&&b<a.length?a[b|0]:null:"string"===typeof a?null!=b&&-1<b&&b<a.length?a.charAt(b|0):null:w(Aa,a)?Ba(a,b):null};
xb.l=function(a,b,c){return null!=a?null!=a&&(a.j&256||u===a.Eb)?a.H(null,b,c):Array.isArray(a)?null!=b&&-1<b&&b<a.length?a[b|0]:c:"string"===typeof a?null!=b&&-1<b&&b<a.length?a.charAt(b|0):c:w(Aa,a)?Ba(a,b,c):c:c};xb.Y=3;var $b=function $b(a){switch(arguments.length){case 3:return $b.l(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $b.J(arguments[0],arguments[1],arguments[2],new M(c.slice(3),0,null))}};
$b.l=function(a,b,c){return null!=a&&(a.j&512||u===a.xb)?a.xa(null,b,c):null!=a?Fa(a,b,c):ac([b,c])};$b.J=function(a,b,c,d){for(;;)if(a=$b.l(a,b,c),v(d))b=N(d),c=N(P(d)),d=P(P(d));else return a};$b.X=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c);c=N(d);d=P(d);return this.J(b,a,c,d)};$b.Y=3;function bc(a,b){this.s=a;this.u=b;this.j=393217;this.A=0}g=bc.prototype;g.P=function(){return this.u};g.R=function(a,b){return new bc(this.s,b)};
g.call=function(a){switch(arguments.length-1){case 0:return this.F();case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);case 3:return this.l(arguments[1],arguments[2],arguments[3]);case 4:return this.fa(arguments[1],arguments[2],arguments[3],arguments[4]);case 5:return this.ua(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 6:return this.Na(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);case 7:return this.Oa(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7]);case 8:return this.Pa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8]);case 9:return this.Qa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9]);case 10:return this.Ca(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10]);
case 11:return this.Da(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11]);case 12:return this.Ea(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12]);case 13:return this.Fa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],
arguments[11],arguments[12],arguments[13]);case 14:return this.Ga(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14]);case 15:return this.Ha(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15]);case 16:return this.Ia(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16]);case 17:return this.Ja(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17]);case 18:return this.Ka(arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18]);case 19:return this.La(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19]);case 20:return this.Ma(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19],arguments[20]);case 21:var b=arguments[1],c=arguments[2],d=arguments[3],e=arguments[4],f=arguments[5],h=arguments[6],k=arguments[7],l=arguments[8],m=arguments[9],n=arguments[10],p=arguments[11],q=arguments[12],t=arguments[13],y=arguments[14],A=arguments[15],
C=arguments[16],F=arguments[17],J=arguments[18],Q=arguments[19],ea=arguments[20],ma=arguments[21];return cc.Db?cc.Db(this.s,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea,ma):cc.call(null,this.s,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea,ma);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.F=function(){return this.s.F?this.s.F():this.s.call(null)};
g.g=function(a){return this.s.g?this.s.g(a):this.s.call(null,a)};g.h=function(a,b){return this.s.h?this.s.h(a,b):this.s.call(null,a,b)};g.l=function(a,b,c){return this.s.l?this.s.l(a,b,c):this.s.call(null,a,b,c)};g.fa=function(a,b,c,d){return this.s.fa?this.s.fa(a,b,c,d):this.s.call(null,a,b,c,d)};g.ua=function(a,b,c,d,e){return this.s.ua?this.s.ua(a,b,c,d,e):this.s.call(null,a,b,c,d,e)};g.Na=function(a,b,c,d,e,f){return this.s.Na?this.s.Na(a,b,c,d,e,f):this.s.call(null,a,b,c,d,e,f)};
g.Oa=function(a,b,c,d,e,f,h){return this.s.Oa?this.s.Oa(a,b,c,d,e,f,h):this.s.call(null,a,b,c,d,e,f,h)};g.Pa=function(a,b,c,d,e,f,h,k){return this.s.Pa?this.s.Pa(a,b,c,d,e,f,h,k):this.s.call(null,a,b,c,d,e,f,h,k)};g.Qa=function(a,b,c,d,e,f,h,k,l){return this.s.Qa?this.s.Qa(a,b,c,d,e,f,h,k,l):this.s.call(null,a,b,c,d,e,f,h,k,l)};g.Ca=function(a,b,c,d,e,f,h,k,l,m){return this.s.Ca?this.s.Ca(a,b,c,d,e,f,h,k,l,m):this.s.call(null,a,b,c,d,e,f,h,k,l,m)};
g.Da=function(a,b,c,d,e,f,h,k,l,m,n){return this.s.Da?this.s.Da(a,b,c,d,e,f,h,k,l,m,n):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n)};g.Ea=function(a,b,c,d,e,f,h,k,l,m,n,p){return this.s.Ea?this.s.Ea(a,b,c,d,e,f,h,k,l,m,n,p):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p)};g.Fa=function(a,b,c,d,e,f,h,k,l,m,n,p,q){return this.s.Fa?this.s.Fa(a,b,c,d,e,f,h,k,l,m,n,p,q):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q)};
g.Ga=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t){return this.s.Ga?this.s.Ga(a,b,c,d,e,f,h,k,l,m,n,p,q,t):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t)};g.Ha=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y){return this.s.Ha?this.s.Ha(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t,y)};g.Ia=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A){return this.s.Ia?this.s.Ia(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A)};
g.Ja=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C){return this.s.Ja?this.s.Ja(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C)};g.Ka=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F){return this.s.Ka?this.s.Ka(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F)};
g.La=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J){return this.s.La?this.s.La(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J)};g.Ma=function(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q){return this.s.Ma?this.s.Ma(a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q):this.s.call(null,a,b,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q)};function dc(a,b){return"function"===typeof a?new bc(a,b):null==a?null:Na(a,b)}
function ec(a){var b=null!=a;return(b?null!=a?a.j&131072||u===a.Hb||(a.j?0:w(La,a)):w(La,a):b)?Ma(a):null}function fc(a){return null!=a?a.j&16777216||u===a.tb?!0:a.j?!1:w(Xa,a):w(Xa,a)}function gc(a){return null==a?!1:null!=a?a.j&1024||u===a.Xb?!0:a.j?!1:w(Ga,a):w(Ga,a)}function hc(a){return null!=a?a.j&67108864||u===a.Zb?!0:a.j?!1:w(Za,a):w(Za,a)}function ic(a){return null!=a?a.j&16384||u===a.$b?!0:a.j?!1:w(Ja,a):w(Ja,a)}function jc(a){return null!=a?a.A&512||u===a.Qb?!0:!1:!1}
function kc(a,b,c,d,e){for(;;){if(0===e)return c;c[d]=a[b];d+=1;--e;b+=1}}var lc={};function mc(a){return null==a?!1:!1===a?!1:!0}function nc(a,b){return null!=a&&(a.j&512||u===a.xb)?a.Ua(null,b):w(Da,a)?Ea(a,b):xb.l(a,b,lc)===lc?!1:!0}function oc(a,b){var c=K(b);return c?(b=N(c),c=P(c),pc?pc(a,b,c):qc.call(null,a,b,c)):a.F?a.F():a.call(null)}function rc(a,b,c){for(c=K(c);;)if(c){var d=N(c);b=a.h?a.h(b,d):a.call(null,b,d);if(Kb(b))return Ka(b);c=P(c)}else return b}
function sc(a,b){a=jb(a);if(v(a.ia()))for(var c=a.next();;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(Kb(c))return Ka(c)}else return c;else return b.F?b.F():b.call(null)}function tc(a,b,c){for(a=jb(a);;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(Kb(c))return Ka(c)}else return c}
function qc(a){switch(arguments.length){case 2:var b=arguments[0],c=arguments[1];return null!=c&&(c.j&524288||u===c.Jb)?c.aa(null,b):Array.isArray(c)?Mb(c,b):"string"===typeof c?Mb(c,b):w(Oa,c)?Pa(c,b):zb(c)?sc(c,b):oc(b,c);case 3:return pc(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}
function pc(a,b,c){return null!=c&&(c.j&524288||u===c.Jb)?c.ba(null,a,b):Array.isArray(c)?Nb(c,a,b):"string"===typeof c?Nb(c,a,b):w(Oa,c)?Pa(c,a,b):zb(c)?tc(c,a,b):rc(a,b,c)}function uc(a,b){return null!=b?Sa(b,a):!0}function vc(a){return a}function wc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}function xc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var z=function z(a){switch(arguments.length){case 0:return z.F();case 1:return z.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return z.J(arguments[0],new M(c.slice(1),0,null))}};z.F=function(){return""};z.g=function(a){return null==a?"":[a].join("")};z.J=function(a,b){for(a=new da(z.g(a));;)if(v(b))a=a.append(z.g(N(b))),b=P(b);else return a.toString()};z.X=function(a){var b=N(a);a=P(a);return this.J(b,a)};z.Y=1;
function Ub(a,b){if(fc(b))if(Pb(a)&&Pb(b)&&T(a)!==T(b))a=!1;else a:for(a=K(a),b=K(b);;){if(null==a){a=null==b;break a}if(null!=b&&R.h(N(a),N(b)))a=P(a),b=P(b);else{a=!1;break a}}else a=null;return mc(a)}function Yb(a,b,c,d,e){this.u=a;this.first=b;this.wa=c;this.count=d;this.v=e;this.j=65937646;this.A=8192}g=Yb.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,this.count)}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){return 1===this.count?null:this.wa};g.V=function(){return this.count};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};
g.W=function(){return Na(O,this.u)};g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return this.first};g.ga=function(){return 1===this.count?O:this.wa};g.I=function(){return this};g.R=function(a,b){return b===this.u?this:new Yb(b,this.first,this.wa,this.count,this.v)};g.U=function(a,b){return new Yb(this.u,b,this,this.count+1,null)};Yb.prototype[qa]=function(){return Db(this)};function yc(a){this.u=a;this.j=65937614;this.A=8192}g=yc.prototype;
g.toString=function(){return lb(this)};g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){return null};g.V=function(){return 0};g.O=function(){return Gb};g.K=function(a,b){return(null!=b?b.j&33554432||u===b.Wb||(b.j?0:w(Ya,b)):w(Ya,b))||fc(b)?null==K(b):!1};g.W=function(){return this};
g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return null};g.ga=function(){return O};g.I=function(){return null};g.R=function(a,b){return b===this.u?this:new yc(b)};g.U=function(a,b){return new Yb(this.u,b,null,1,null)};var O=new yc(null);yc.prototype[qa]=function(){return Db(this)};function zc(a,b,c,d){this.u=a;this.first=b;this.wa=c;this.v=d;this.j=65929452;this.A=8192}g=zc.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){return null==this.wa?null:K(this.wa)};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};g.W=function(){return O};
g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return this.first};g.ga=function(){return null==this.wa?O:this.wa};g.I=function(){return this};g.R=function(a,b){return b===this.u?this:new zc(b,this.first,this.wa,this.v)};g.U=function(a,b){return new zc(null,b,this,null)};zc.prototype[qa]=function(){return Db(this)};function V(a,b){return null==b?new Yb(null,a,null,1,null):null!=b&&(b.j&64||u===b.Za)?new zc(null,a,b,null):new zc(null,a,K(b),null)}
function I(a,b,c,d){this.fb=a;this.name=b;this.va=c;this.Ta=d;this.j=2153775105;this.A=4096}g=I.prototype;g.toString=function(){return[":",z.g(this.va)].join("")};g.K=function(a,b){return b instanceof I?this.va===b.va:!1};g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};
g.g=function(a){return xb.h(a,this)};g.h=function(a,b){return xb.l(a,this,b)};g.O=function(){var a=this.Ta;return null!=a?a:this.Ta=a=vb(qb(this.name),tb(this.fb))+2654435769|0};g.M=function(a,b){return H(b,[":",z.g(this.va)].join(""))};function Ac(a){if(null!=a&&(a.A&4096||u===a.Ib))return a.fb;throw Error(["Doesn't support namespace: ",z.g(a)].join(""));}
var Bc=function Bc(a){switch(arguments.length){case 1:return Bc.g(arguments[0]);case 2:return Bc.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};Bc.g=function(a){if(a instanceof I)return a;if(a instanceof wb)return new I(Ac(a),Cc.g?Cc.g(a):Cc.call(null,a),a.Aa,null);if(R.h("/",a))return new I(null,a,a,null);if("string"===typeof a){var b=a.split("/");return 2===b.length?new I(b[0],b[1],a,null):new I(null,b[0],a,null)}return null};
Bc.h=function(a,b){a=a instanceof I?Cc.g?Cc.g(a):Cc.call(null,a):a instanceof wb?Cc.g?Cc.g(a):Cc.call(null,a):a;b=b instanceof I?Cc.g?Cc.g(b):Cc.call(null,b):b instanceof wb?Cc.g?Cc.g(b):Cc.call(null,b):b;return new I(a,b,[v(a)?[z.g(a),"/"].join(""):null,z.g(b)].join(""),null)};Bc.Y=2;function Dc(a,b,c){this.u=a;this.ab=b;this.C=null;this.v=c;this.j=32374988;this.A=1}g=Dc.prototype;g.toString=function(){return lb(this)};
function Ec(a){null!=a.ab&&(a.C=a.ab.F?a.ab.F():a.ab.call(null),a.ab=null);return a.C}g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){this.I(null);return null==this.C?null:P(this.C)};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};g.W=function(){return Na(O,this.u)};
g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){this.I(null);return null==this.C?null:N(this.C)};g.ga=function(){this.I(null);return null!=this.C?Bb(this.C):O};g.I=function(){Ec(this);if(null==this.C)return null;for(var a=this.C;;)if(a instanceof Dc)a=Ec(a);else return this.C=a,K(this.C)};g.R=function(a,b){var c=this;return b===this.u?c:new Dc(b,function(){return c.I(null)},this.v)};g.U=function(a,b){return V(b,this)};Dc.prototype[qa]=function(){return Db(this)};
function Fc(a){this.lb=a;this.end=0;this.j=2;this.A=0}Fc.prototype.add=function(a){this.lb[this.end]=a;return this.end+=1};Fc.prototype.ta=function(){var a=new Gc(this.lb,0,this.end);this.lb=null;return a};Fc.prototype.V=function(){return this.end};function Gc(a,b,c){this.i=a;this.S=b;this.end=c;this.j=524306;this.A=0}g=Gc.prototype;g.V=function(){return this.end-this.S};g.T=function(a,b){return this.i[this.S+b]};g.la=function(a,b,c){return 0<=b&&b<this.end-this.S?this.i[this.S+b]:c};
g.qb=function(){if(this.S===this.end)throw Error("-drop-first of empty chunk");return new Gc(this.i,this.S+1,this.end)};g.aa=function(a,b){return Ob(this.i,b,this.i[this.S],this.S+1)};g.ba=function(a,b,c){return Ob(this.i,b,c,this.S)};function Hc(a,b,c,d){this.ta=a;this.oa=b;this.u=c;this.v=d;this.j=31850732;this.A=1536}g=Hc.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){return 1<sa(this.ta)?new Hc(fb(this.ta),this.oa,null,null):null==this.oa?null:Wa(this.oa)};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};
g.K=function(a,b){return Ub(this,b)};g.W=function(){return O};g.ca=function(){return D(this.ta,0)};g.ga=function(){return 1<sa(this.ta)?new Hc(fb(this.ta),this.oa,null,null):null==this.oa?O:this.oa};g.I=function(){return this};g.mb=function(){return this.ta};g.gb=function(){return null==this.oa?O:this.oa};g.R=function(a,b){return b===this.u?this:new Hc(this.ta,this.oa,b,this.v)};g.U=function(a,b){return V(b,this)};g.rb=function(){return null==this.oa?null:this.oa};Hc.prototype[qa]=function(){return Db(this)};
function Ic(a,b){return 0===sa(a)?b:new Hc(a,b,null,null)}function Jc(a,b){a.add(b)}function Kc(a,b){if(Pb(b))return T(b);var c=0;for(b=K(b);;)if(null!=b&&c<a)c+=1,b=P(b);else return c}var Lc=function Lc(a){if(null==a)return null;var c=P(a);return null==c?K(N(a)):V(N(a),Lc.g?Lc.g(c):Lc.call(null,c))};
function Mc(a,b,c){var d=K(c);if(0===b)return a.F?a.F():a.call(null);c=E(d);var e=G(d);if(1===b)return a.g?a.g(c):a.call(null,c);d=E(e);var f=G(e);if(2===b)return a.h?a.h(c,d):a.call(null,c,d);e=E(f);var h=G(f);if(3===b)return a.l?a.l(c,d,e):a.call(null,c,d,e);f=E(h);var k=G(h);if(4===b)return a.fa?a.fa(c,d,e,f):a.call(null,c,d,e,f);h=E(k);var l=G(k);if(5===b)return a.ua?a.ua(c,d,e,f,h):a.call(null,c,d,e,f,h);k=E(l);var m=G(l);if(6===b)return a.Na?a.Na(c,d,e,f,h,k):a.call(null,c,d,e,f,h,k);l=E(m);
var n=G(m);if(7===b)return a.Oa?a.Oa(c,d,e,f,h,k,l):a.call(null,c,d,e,f,h,k,l);m=E(n);var p=G(n);if(8===b)return a.Pa?a.Pa(c,d,e,f,h,k,l,m):a.call(null,c,d,e,f,h,k,l,m);n=E(p);var q=G(p);if(9===b)return a.Qa?a.Qa(c,d,e,f,h,k,l,m,n):a.call(null,c,d,e,f,h,k,l,m,n);p=E(q);var t=G(q);if(10===b)return a.Ca?a.Ca(c,d,e,f,h,k,l,m,n,p):a.call(null,c,d,e,f,h,k,l,m,n,p);q=E(t);var y=G(t);if(11===b)return a.Da?a.Da(c,d,e,f,h,k,l,m,n,p,q):a.call(null,c,d,e,f,h,k,l,m,n,p,q);t=E(y);var A=G(y);if(12===b)return a.Ea?
a.Ea(c,d,e,f,h,k,l,m,n,p,q,t):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t);y=E(A);var C=G(A);if(13===b)return a.Fa?a.Fa(c,d,e,f,h,k,l,m,n,p,q,t,y):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y);A=E(C);var F=G(C);if(14===b)return a.Ga?a.Ga(c,d,e,f,h,k,l,m,n,p,q,t,y,A):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y,A);C=E(F);var J=G(F);if(15===b)return a.Ha?a.Ha(c,d,e,f,h,k,l,m,n,p,q,t,y,A,C):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C);F=E(J);var Q=G(J);if(16===b)return a.Ia?a.Ia(c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F):a.call(null,
c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F);J=E(Q);var ea=G(Q);if(17===b)return a.Ja?a.Ja(c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J);Q=E(ea);var ma=G(ea);if(18===b)return a.Ka?a.Ka(c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q);ea=E(ma);ma=G(ma);if(19===b)return a.La?a.La(c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea);var Ld=E(ma);G(ma);if(20===b)return a.Ma?a.Ma(c,d,e,f,h,k,l,m,n,p,q,t,
y,A,C,F,J,Q,ea,Ld):a.call(null,c,d,e,f,h,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea,Ld);throw Error("Only up to 20 arguments supported on functions");}function Nc(a){return null!=a&&(a.j&128||u===a.Ya)?a.Z():K(Bb(a))}function Oc(a,b,c){return null==c?a.g?a.g(b):a.call(a,b):Pc(a,b,E(c),Nc(c))}function Pc(a,b,c,d){return null==d?a.h?a.h(b,c):a.call(a,b,c):Qc(a,b,c,E(d),Nc(d))}function Qc(a,b,c,d,e){return null==e?a.l?a.l(b,c,d):a.call(a,b,c,d):Rc(a,b,c,d,E(e),Nc(e))}
function Rc(a,b,c,d,e,f){if(null==f)return a.fa?a.fa(b,c,d,e):a.call(a,b,c,d,e);var h=E(f),k=P(f);if(null==k)return a.ua?a.ua(b,c,d,e,h):a.call(a,b,c,d,e,h);f=E(k);var l=P(k);if(null==l)return a.Na?a.Na(b,c,d,e,h,f):a.call(a,b,c,d,e,h,f);k=E(l);var m=P(l);if(null==m)return a.Oa?a.Oa(b,c,d,e,h,f,k):a.call(a,b,c,d,e,h,f,k);l=E(m);var n=P(m);if(null==n)return a.Pa?a.Pa(b,c,d,e,h,f,k,l):a.call(a,b,c,d,e,h,f,k,l);m=E(n);var p=P(n);if(null==p)return a.Qa?a.Qa(b,c,d,e,h,f,k,l,m):a.call(a,b,c,d,e,h,f,k,l,
m);n=E(p);var q=P(p);if(null==q)return a.Ca?a.Ca(b,c,d,e,h,f,k,l,m,n):a.call(a,b,c,d,e,h,f,k,l,m,n);p=E(q);var t=P(q);if(null==t)return a.Da?a.Da(b,c,d,e,h,f,k,l,m,n,p):a.call(a,b,c,d,e,h,f,k,l,m,n,p);q=E(t);var y=P(t);if(null==y)return a.Ea?a.Ea(b,c,d,e,h,f,k,l,m,n,p,q):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q);t=E(y);var A=P(y);if(null==A)return a.Fa?a.Fa(b,c,d,e,h,f,k,l,m,n,p,q,t):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q,t);y=E(A);var C=P(A);if(null==C)return a.Ga?a.Ga(b,c,d,e,h,f,k,l,m,n,p,q,t,y):a.call(a,b,
c,d,e,h,f,k,l,m,n,p,q,t,y);A=E(C);var F=P(C);if(null==F)return a.Ha?a.Ha(b,c,d,e,h,f,k,l,m,n,p,q,t,y,A):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q,t,y,A);C=E(F);var J=P(F);if(null==J)return a.Ia?a.Ia(b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C);F=E(J);var Q=P(J);if(null==Q)return a.Ja?a.Ja(b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F);J=E(Q);var ea=P(Q);if(null==ea)return a.Ka?a.Ka(b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F,J):a.call(a,b,c,d,e,h,f,k,l,m,
n,p,q,t,y,A,C,F,J);Q=E(ea);var ma=P(ea);if(null==ma)return a.La?a.La(b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F,J,Q):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F,J,Q);ea=E(ma);ma=P(ma);if(null==ma)return a.Ma?a.Ma(b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea):a.call(a,b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea);b=[b,c,d,e,h,f,k,l,m,n,p,q,t,y,A,C,F,J,Q,ea];for(c=ma;;)if(c)b.push(E(c)),c=P(c);else break;return a.apply(a,b)}
function cc(a){switch(arguments.length){case 2:return Sc(arguments[0],arguments[1]);case 3:return Tc(arguments[0],arguments[1],arguments[2]);case 4:var b=arguments[0];var c=arguments[1],d=arguments[2],e=arguments[3];b.X?(c=V(c,V(d,e)),d=b.Y,e=2+Kc(d-1,e),b=e<=d?Mc(b,e,c):b.X(c)):b=Pc(b,c,d,K(e));return b;case 5:b=arguments[0];c=arguments[1];d=arguments[2];var f=arguments[3];e=arguments[4];b.X?(c=V(c,V(d,V(f,e))),d=b.Y,e=3+Kc(d-2,e),b=e<=d?Mc(b,e,c):b.X(c)):b=Qc(b,c,d,f,K(e));return b;default:e=[];
b=arguments.length;for(c=0;;)if(c<b)e.push(arguments[c]),c+=1;else break;b=arguments[0];c=arguments[1];d=arguments[2];f=arguments[3];var h=arguments[4];e=new M(e.slice(5),0,null);b.X?(e=Lc(e),c=V(c,V(d,V(f,V(h,e)))),d=b.Y,e=4+Kc(d-3,e),b=e<=d?Mc(b,e,c):b.X(c)):b=Rc(b,c,d,f,h,Lc(e));return b}}function Sc(a,b){if(a.X){var c=a.Y,d=Kc(c+1,b);return d<=c?Mc(a,d,b):a.X(b)}b=K(b);return null==b?a.F?a.F():a.call(a):Oc(a,E(b),Nc(b))}
function Tc(a,b,c){if(a.X){b=V(b,c);var d=a.Y;c=Kc(d,c)+1;return c<=d?Mc(a,c,b):a.X(b)}return Oc(a,b,K(c))}function Uc(a){if(null!=a&&(a.j&64||u===a.Za))if(P(a)){a:{var b=[];for(a=K(a);;)if(null!=a)b.push(N(a)),a=P(a);else break a}b=ac(b)}else b=K(a)?N(a):Vc;else b=a;return b}function Wc(a){this.Nb=a;this.j=393216;this.A=0}g=Wc.prototype;g.R=function(a,b){return new Wc(b)};g.P=function(){return this.Nb};g.ia=function(){return!1};g.next=function(){return Error("No such element")};g.remove=function(){return Error("Unsupported operation")};
function Xc(a,b){for(;;){if(null==K(b))return!0;var c=N(b);c=a.g?a.g(c):a.call(null,c);if(v(c))b=P(b);else return!1}}
var X=function X(a){switch(arguments.length){case 1:return X.g(arguments[0]);case 2:return X.h(arguments[0],arguments[1]);case 3:return X.l(arguments[0],arguments[1],arguments[2]);case 4:return X.fa(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X.J(arguments[0],arguments[1],arguments[2],arguments[3],new M(c.slice(4),0,null))}};
X.g=function(a){return function(b){return function(){function c(k,l){l=a.g?a.g(l):a.call(null,l);return b.h?b.h(k,l):b.call(null,k,l)}function d(k){return b.g?b.g(k):b.call(null,k)}function e(){return b.F?b.F():b.call(null)}var f=null,h=function(){function k(m,n,p){var q=null;if(2<arguments.length){q=0;for(var t=Array(arguments.length-2);q<t.length;)t[q]=arguments[q+2],++q;q=new M(t,0,null)}return l.call(this,m,n,q)}function l(m,n,p){n=Tc(a,n,p);return b.h?b.h(m,n):b.call(null,m,n)}k.Y=2;k.X=function(m){var n=
N(m);m=P(m);var p=N(m);m=Bb(m);return l(n,p,m)};k.J=l;return k}();f=function(k,l,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,k);case 2:return c.call(this,k,l);default:var n=null;if(2<arguments.length){n=0;for(var p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new M(p,0,null)}return h.J(k,l,n)}throw Error("Invalid arity: "+arguments.length);};f.Y=2;f.X=h.X;f.F=e;f.g=d;f.h=c;f.J=h.J;return f}()}};
X.h=function(a,b){return new Dc(null,function(){var c=K(b);if(c){if(jc(c)){for(var d=gb(c),e=T(d),f=new Fc(Array(e)),h=0;;)if(h<e)Jc(f,function(){var k=D(d,h);return a.g?a.g(k):a.call(null,k)}()),h+=1;else break;return Ic(f.ta(),X.h(a,hb(c)))}return V(function(){var k=N(c);return a.g?a.g(k):a.call(null,k)}(),X.h(a,Bb(c)))}return null},null)};
X.l=function(a,b,c){return new Dc(null,function(){var d=K(b),e=K(c);if(d&&e){var f=N(d);var h=N(e);f=a.h?a.h(f,h):a.call(null,f,h);d=V(f,X.l(a,Bb(d),Bb(e)))}else d=null;return d},null)};X.fa=function(a,b,c,d){return new Dc(null,function(){var e=K(b),f=K(c),h=K(d);if(e&&f&&h){var k=N(e);var l=N(f),m=N(h);k=a.l?a.l(k,l,m):a.call(null,k,l,m);e=V(k,X.fa(a,Bb(e),Bb(f),Bb(h)))}else e=null;return e},null)};
X.J=function(a,b,c,d,e){return X.h(function(f){return Sc(a,f)},function k(h){return new Dc(null,function(){var l=X.h(K,h);return Xc(vc,l)?V(X.h(N,l),k(X.h(Bb,l))):null},null)}(Wb.J(e,d,Vb([c,b]))))};X.X=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c);c=N(d);var e=P(d);d=N(e);e=P(e);return this.J(b,a,c,d,e)};X.Y=4;function Yc(a,b){return null!=a?null!=a&&(a.A&4||u===a.Sb)?Na(db(pc(cb,bb(a),b)),ec(a)):pc(wa,a,b):pc(Wb,a,b)}function Zc(a,b){this.D=a;this.i=b}
function $c(a){return new Zc(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function ad(a){a=a.m;return 32>a?0:a-1>>>5<<5}function bd(a,b,c){for(;;){if(0===b)return c;var d=$c(a);d.i[0]=c;c=d;b-=5}}var cd=function cd(a,b,c,d){var f=new Zc(c.D,B(c.i)),h=a.m-1>>>b&31;5===b?f.i[h]=d:(c=c.i[h],null!=c?(b-=5,a=cd.fa?cd.fa(a,b,c,d):cd.call(null,a,b,c,d)):a=bd(null,b-5,d),f.i[h]=a);return f};
function dd(a,b){if(b>=ad(a))return a.ea;var c=a.root;for(a=a.shift;;)if(0<a){var d=a-5;c=c.i[b>>>a&31];a=d}else return c.i}function ed(a,b){if(0<=b&&b<a.m)b=dd(a,b);else throw a=a.m,Error(["No item ",z.g(b)," in vector of length ",z.g(a)].join(""));return b}var fd=function fd(a,b,c,d,e){var h=new Zc(c.D,B(c.i));if(0===b)h.i[d&31]=e;else{var k=d>>>b&31;b-=5;c=c.i[k];a=fd.ua?fd.ua(a,b,c,d,e):fd.call(null,a,b,c,d,e);h.i[k]=a}return h};
function gd(a,b,c){this.kb=this.o=0;this.i=a;this.Pb=b;this.start=0;this.end=c}gd.prototype.ia=function(){return this.o<this.end};gd.prototype.next=function(){32===this.o-this.kb&&(this.i=dd(this.Pb,this.o),this.kb+=32);var a=this.i[this.o&31];this.o+=1;return a};function hd(a,b,c,d){return c<d?id(a,b,Rb(a,c),c+1,d):b.F?b.F():b.call(null)}
function id(a,b,c,d,e){var f=c;c=d;for(d=dd(a,d);;)if(c<e){var h=c&31;d=0===h?dd(a,c):d;h=d[h];f=b.h?b.h(f,h):b.call(null,f,h);if(Kb(f))return Ka(f);c+=1}else return f}function Y(a,b,c,d,e,f){this.u=a;this.m=b;this.shift=c;this.root=d;this.ea=e;this.v=f;this.j=167666463;this.A=139268}g=Y.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.ka=function(a,b){return this.H(null,b,null)};g.H=function(a,b,c){return"number"===typeof b?this.la(null,b,c):c};
g.hb=function(a,b,c){a=0;for(var d=c;;)if(a<this.m){var e=dd(this,a);c=e.length;a:for(var f=0;;)if(f<c){var h=f+a,k=e[f];d=b.l?b.l(d,h,k):b.call(null,d,h,k);if(Kb(d)){e=d;break a}f+=1}else{e=d;break a}if(Kb(e))return Ka(e);a+=c;d=e}else return d};g.T=function(a,b){return ed(this,b)[b&31]};g.la=function(a,b,c){return 0<=b&&b<this.m?dd(this,b)[b&31]:c};
g.nb=function(a,b){if(0<=a&&a<this.m){if(ad(this)<=a){var c=B(this.ea);c[a&31]=b;return new Y(this.u,this.m,this.shift,this.root,c,null)}return new Y(this.u,this.m,this.shift,fd(this,this.shift,this.root,a,b),this.ea,null)}if(a===this.m)return this.U(null,b);throw Error(["Index ",z.g(a)," out of bounds  [0,",z.g(this.m),"]"].join(""));};g.sa=function(){var a=this.m;return new gd(0<T(this)?dd(this,0):null,this,a)};g.P=function(){return this.u};g.V=function(){return this.m};
g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){if(b instanceof Y)if(this.m===T(b))for(a=this.sa(null),b=b.sa(null);;)if(a.ia()){var c=a.next(),d=b.next();if(!R.h(c,d))return!1}else return!0;else return!1;else return Ub(this,b)};g.Xa=function(){return new jd(this.m,this.shift,kd.g?kd.g(this.root):kd.call(null,this.root),ld.g?ld.g(this.ea):ld.call(null,this.ea))};g.W=function(){return Na(Xb,this.u)};g.aa=function(a,b){return hd(this,b,0,this.m)};
g.ba=function(a,b,c){a=0;for(var d=c;;)if(a<this.m){var e=dd(this,a);c=e.length;a:for(var f=0;;)if(f<c){var h=e[f];d=b.h?b.h(d,h):b.call(null,d,h);if(Kb(d)){e=d;break a}f+=1}else{e=d;break a}if(Kb(e))return Ka(e);a+=c;d=e}else return d};g.xa=function(a,b,c){if("number"===typeof b)return this.nb(b,c);throw Error("Vector's key for assoc must be a number.");};g.Ua=function(a,b){return"number"!==typeof b||isNaN(b)||Infinity===b||parseFloat(b)!==parseInt(b,10)?!1:0<=b&&b<this.m};
g.I=function(){if(0===this.m)return null;if(32>=this.m)return new M(this.ea,0,null);a:{var a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.i[0];else{a=a.i;break a}}return md?md(this,a,0,0):nd.call(null,this,a,0,0)};g.R=function(a,b){return b===this.u?this:new Y(b,this.m,this.shift,this.root,this.ea,this.v)};
g.U=function(a,b){if(32>this.m-ad(this)){a=this.ea.length;for(var c=Array(a+1),d=0;;)if(d<a)c[d]=this.ea[d],d+=1;else break;c[a]=b;return new Y(this.u,this.m+1,this.shift,this.root,c,null)}a=(c=this.m>>>5>1<<this.shift)?this.shift+5:this.shift;c?(c=$c(null),c.i[0]=this.root,d=bd(null,this.shift,new Zc(null,this.ea)),c.i[1]=d):c=cd(this,this.shift,this.root,new Zc(null,this.ea));return new Y(this.u,this.m+1,a,c,[b],null)};
g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.g=function(a){if("number"===typeof a)return this.T(null,a);throw Error("Key must be integer");};
var od=new Zc(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Xb=new Y(null,0,5,od,[],Gb);Y.prototype[qa]=function(){return Db(this)};function pd(a,b,c,d,e){this.ja=a;this.node=b;this.o=c;this.S=d;this.u=e;this.v=null;this.j=32375020;this.A=1536}g=pd.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){if(this.S+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.S+1;a=md?md(a,b,c,d):nd.call(null,a,b,c,d);return null==a?null:a}return this.rb()};
g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};g.W=function(){return O};g.aa=function(a,b){return hd(this.ja,b,this.o+this.S,T(this.ja))};g.ba=function(a,b,c){return id(this.ja,b,c,this.o+this.S,T(this.ja))};g.ca=function(){return this.node[this.S]};g.ga=function(){if(this.S+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.S+1;a=md?md(a,b,c,d):nd.call(null,a,b,c,d);return null==a?O:a}return this.gb(null)};g.I=function(){return this};
g.mb=function(){var a=this.node;return new Gc(a,this.S,a.length)};g.gb=function(){var a=this.o+this.node.length;if(a<sa(this.ja)){var b=this.ja,c=dd(this.ja,a);return md?md(b,c,a,0):nd.call(null,b,c,a,0)}return O};g.R=function(a,b){return b===this.u?this:qd?qd(this.ja,this.node,this.o,this.S,b):nd.call(null,this.ja,this.node,this.o,this.S,b)};g.U=function(a,b){return V(b,this)};
g.rb=function(){var a=this.o+this.node.length;if(a<sa(this.ja)){var b=this.ja,c=dd(this.ja,a);return md?md(b,c,a,0):nd.call(null,b,c,a,0)}return null};pd.prototype[qa]=function(){return Db(this)};
function nd(a){switch(arguments.length){case 3:var b=arguments[0],c=arguments[1],d=arguments[2];return new pd(b,ed(b,c),c,d,null);case 4:return md(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return qd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function md(a,b,c,d){return new pd(a,b,c,d,null)}function qd(a,b,c,d,e){return new pd(a,b,c,d,e)}
function rd(a,b){return a===b.D?b:new Zc(a,B(b.i))}function kd(a){return new Zc({},B(a.i))}function ld(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];kc(a,0,b,0,a.length);return b}var sd=function sd(a,b,c,d){c=rd(a.root.D,c);var f=a.m-1>>>b&31;if(5===b)a=d;else{var h=c.i[f];null!=h?(b-=5,a=sd.fa?sd.fa(a,b,h,d):sd.call(null,a,b,h,d)):a=bd(a.root.D,b-5,d)}c.i[f]=a;return c};
function jd(a,b,c,d){this.m=a;this.shift=b;this.root=c;this.ea=d;this.A=88;this.j=275}g=jd.prototype;
g.$a=function(a,b){if(this.root.D){if(32>this.m-ad(this))this.ea[this.m&31]=b;else{a=new Zc(this.root.D,this.ea);var c=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];c[0]=b;this.ea=c;this.m>>>5>1<<this.shift?(b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],c=this.shift+
5,b[0]=this.root,b[1]=bd(this.root.D,this.shift,a),this.root=new Zc(this.root.D,b),this.shift=c):this.root=sd(this,this.shift,this.root,a)}this.m+=1;return this}throw Error("conj! after persistent!");};g.ib=function(){if(this.root.D){this.root.D=null;var a=this.m-ad(this),b=Array(a);kc(this.ea,0,b,0,a);return new Y(null,this.m,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
g.Va=function(a,b,c){if("number"===typeof b)return td(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
function td(a,b,c){if(a.root.D){if(0<=b&&b<a.m){if(ad(a)<=b)a.ea[b&31]=c;else{var d=function k(f,h){h=rd(a.root.D,h);if(0===f)h.i[b&31]=c;else{var l=b>>>f&31;f=k(f-5,h.i[l]);h.i[l]=f}return h}(a.shift,a.root);a.root=d}return a}if(b===a.m)return a.$a(null,c);throw Error(["Index ",z.g(b)," out of bounds for TransientVector of length",z.g(a.m)].join(""));}throw Error("assoc! after persistent!");}g.V=function(){if(this.root.D)return this.m;throw Error("count after persistent!");};
g.T=function(a,b){if(this.root.D)return ed(this,b)[b&31];throw Error("nth after persistent!");};g.la=function(a,b,c){return 0<=b&&b<this.m?this.T(null,b):c};g.ka=function(a,b){return this.H(null,b,null)};g.H=function(a,b,c){if(this.root.D)return"number"===typeof b?this.la(null,b,c):c;throw Error("lookup after persistent!");};
g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.g=function(a){return this.ka(null,a)};g.h=function(a,b){return this.H(null,a,b)};function ud(){this.j=2097152;this.A=0}ud.prototype.K=function(){return!1};var vd=new ud;
function wd(a,b){return mc(gc(b)&&!hc(b)?T(a)===T(b)?(null!=a?a.j&1048576||u===a.Vb||(a.j?0:w(Ra,a)):w(Ra,a))?uc(function(c,d,e){return R.h(xb.l(b,d,vd),e)?!0:new Jb},a):Xc(function(c){return R.h(xb.l(b,N(c),vd),N(P(c)))},a):null:null)}function xd(a){this.C=a}xd.prototype.next=function(){if(null!=this.C){var a=N(this.C),b=W(a,0,null);a=W(a,1,null);this.C=P(this.C);return{value:[b,a],done:!1}}return{value:null,done:!0}};
function yd(a,b){if(b instanceof I)a:{var c=a.length;b=b.va;for(var d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof I&&b===a[d].va){a=d;break a}d+=2}}else if("string"===typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(b===a[d]){a=d;break a}d+=2}else if(b instanceof wb)a:for(c=a.length,b=b.Aa,d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof wb&&b===a[d].Aa){a=d;break a}d+=2}else if(null==b)a:for(b=a.length,c=0;;){if(b<=c){a=-1;break a}if(null==a[c]){a=c;break a}c+=2}else a:for(c=
a.length,d=0;;){if(c<=d){a=-1;break a}if(R.h(b,a[d])){a=d;break a}d+=2}return a}function zd(a,b){this.key=a;this.G=b;this.v=null;this.j=166619935;this.A=0}g=zd.prototype;g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.ka=function(a,b){return this.la(null,b,null)};g.H=function(a,b,c){return this.la(null,b,c)};g.T=function(a,b){if(0===b)return this.key;if(1===b)return this.G;throw Error("Index out of bounds");};
g.la=function(a,b,c){return 0===b?this.key:1===b?this.G:c};g.nb=function(a,b){return(new Y(null,2,5,od,[this.key,this.G],null)).nb(a,b)};g.P=function(){return null};g.V=function(){return 2};g.Fb=function(){return this.key};g.Gb=function(){return this.G};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};g.W=function(){return null};
g.aa=function(a,b){a:if(a=this.V(null),0===a)b=b.F?b.F():b.call(null);else for(var c=this.T(null,0),d=1;;)if(d<a){var e=this.T(null,d);c=b.h?b.h(c,e):b.call(null,c,e);if(Kb(c)){b=Ka(c);break a}d+=1}else{b=c;break a}return b};g.ba=function(a,b,c){a:{a=this.V(null);var d=c;for(c=0;;)if(c<a){var e=this.T(null,c);d=b.h?b.h(d,e):b.call(null,d,e);if(Kb(d)){b=Ka(d);break a}c+=1}else{b=d;break a}}return b};g.xa=function(a,b,c){return $b.l(new Y(null,2,5,od,[this.key,this.G],null),b,c)};
g.Ua=function(a,b){return 0===b||1===b};g.I=function(){return new M([this.key,this.G],0,null)};g.R=function(a,b){return dc(new Y(null,2,5,od,[this.key,this.G],null),b)};g.U=function(a,b){return new Y(null,3,5,od,[this.key,this.G,b],null)};g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};
g.g=function(a){return this.T(null,a)};g.h=function(a,b){return this.la(null,a,b)};function Ad(a){return null!=a?a.j&2048||u===a.Yb?!0:!1:!1}function Bd(a,b,c){this.i=a;this.o=b;this.ra=c;this.j=32374990;this.A=0}g=Bd.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.ra};g.Z=function(){return this.o<this.i.length-2?new Bd(this.i,this.o+2,null):null};g.V=function(){return(this.i.length-this.o)/2};g.O=function(){return Fb(this)};g.K=function(a,b){return Ub(this,b)};
g.W=function(){return O};g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return new zd(this.i[this.o],this.i[this.o+1])};g.ga=function(){return this.o<this.i.length-2?new Bd(this.i,this.o+2,null):O};g.I=function(){return this};g.R=function(a,b){return b===this.ra?this:new Bd(this.i,this.o,b)};g.U=function(a,b){return V(b,this)};Bd.prototype[qa]=function(){return Db(this)};function Cd(a,b){this.i=a;this.o=0;this.m=b}
Cd.prototype.ia=function(){return this.o<this.m};Cd.prototype.next=function(){var a=new zd(this.i[this.o],this.i[this.o+1]);this.o+=2;return a};function ia(a,b,c,d){this.u=a;this.m=b;this.i=c;this.v=d;this.j=16647951;this.A=139268}g=ia.prototype;g.toString=function(){return lb(this)};g.keys=function(){return Db(Dd.g?Dd.g(this):Dd.call(null,this))};g.entries=function(){return new xd(K(K(this)))};g.values=function(){return Db(Ed.g?Ed.g(this):Ed.call(null,this))};g.has=function(a){return nc(this,a)};
g.get=function(a,b){return this.H(null,a,b)};g.forEach=function(a){for(var b=K(this),c=null,d=0,e=0;;)if(e<d){var f=c.T(null,e),h=W(f,0,null);f=W(f,1,null);a.h?a.h(f,h):a.call(null,f,h);e+=1}else if(b=K(b))jc(b)?(c=gb(b),b=hb(b),h=c,d=T(c),c=h):(c=N(b),h=W(c,0,null),f=W(c,1,null),a.h?a.h(f,h):a.call(null,f,h),b=P(b),c=null,d=0),e=0;else return null};g.ka=function(a,b){return this.H(null,b,null)};g.H=function(a,b,c){a=yd(this.i,b);return-1===a?c:this.i[a+1]};
g.hb=function(a,b,c){a=this.i.length;for(var d=0;;)if(d<a){var e=this.i[d],f=this.i[d+1];c=b.l?b.l(c,e,f):b.call(null,c,e,f);if(Kb(c))return Ka(c);d+=2}else return c};g.sa=function(){return new Cd(this.i,2*this.m)};g.P=function(){return this.u};g.V=function(){return this.m};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Hb(this)};
g.K=function(a,b){if(gc(b)&&!hc(b))if(a=this.i.length,this.m===b.V(null))for(var c=0;;)if(c<a){var d=b.H(null,this.i[c],lc);if(d!==lc)if(R.h(this.i[c+1],d))c+=2;else return!1;else return!1}else return!0;else return!1;else return!1};g.Xa=function(){return new Fd(this.i.length,B(this.i))};g.W=function(){return Na(Vc,this.u)};g.aa=function(a,b){return sc(this,b)};g.ba=function(a,b,c){return tc(this,b,c)};
g.xa=function(a,b,c){a=yd(this.i,b);if(-1===a){if(this.m<Gd){a=this.i;for(var d=a.length,e=Array(d+2),f=0;;)if(f<d)e[f]=a[f],f+=1;else break;e[d]=b;e[d+1]=c;return new ia(this.u,this.m+1,e,null)}return Na(Fa(Yc(Hd,this),b,c),this.u)}if(c===this.i[a+1])return this;b=B(this.i);b[a+1]=c;return new ia(this.u,this.m,b,null)};g.Ua=function(a,b){return-1!==yd(this.i,b)};g.I=function(){var a=this.i;return 0<=a.length-2?new Bd(a,0,null):null};
g.R=function(a,b){return b===this.u?this:new ia(b,this.m,this.i,this.v)};g.U=function(a,b){if(ic(b))return this.xa(null,D(b,0),D(b,1));a=this;for(b=K(b);;){if(null==b)return a;var c=N(b);if(ic(c))a=Fa(a,D(c,0),D(c,1)),b=P(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.g=function(a){return this.ka(null,a)};g.h=function(a,b){return this.H(null,a,b)};var Vc=new ia(null,0,[],Ib),Gd=8;function Id(a,b){return a===b?!0:a===b||a instanceof I&&b instanceof I&&a.va===b.va?!0:R.h(a,b)}
function Jd(a){for(var b=0,c=0;;)if(b<a.length){var d;a:for(d=0;;)if(d<b){var e=Id(a[b],a[d]);if(e){d=e;break a}d=2+d}else{d=!1;break a}c=d?c:c+2;b=2+b}else return c}function Kd(a,b){var c=a.length-1,d=K(b);b=Array(c+2*T(d));a=kc(a,0,b,0,c);for(b=c;;)if(d){var e=N(d);a[b]=Ha(e);a[b+1]=Ia(e);b=2+c;d=P(d)}else return a}
function ac(a){var b=a.length,c=1===(b&1),d;if(!(d=c))a:for(d=0;;)if(d<a.length){var e;b:for(e=0;;)if(e<d){var f=Id(a[d],a[e]);if(f){e=f;break b}e=2+e}else{e=!1;break b}if(e){d=e;break a}d=2+d}else{d=!1;break a}return d?Md(a,c):new ia(null,b/2,a,null)}
function Md(a,b){var c=b?Kd(a,Yc(Vc,a[a.length-1])):a;a=Jd(c);var d=c.length;if(a<d){a=Array(a);for(var e=0,f=0;;)if(e<d)(function(){for(var h=0;;)if(h<f){var k=Id(c[e],c[h]);if(k)return k;h=2+h}else return!1})()?(b=f,e=2+e,f=b):(b=function(){for(var h=d-2;;)if(h>=e){if(Id(c[e],c[h]))return h;h-=2}else return h}(),a[f]=c[e],a[f+1]=c[b+1],b=2+f,e=2+e,f=b);else break;return new ia(null,a.length/2,a,null)}return new ia(null,c.length/2,c,null)}ia.prototype[qa]=function(){return Db(this)};
function Fd(a,b){this.Wa={};this.Sa=a;this.i=b;this.j=259;this.A=56}g=Fd.prototype;g.V=function(){if(this.Wa)return wc(this.Sa);throw Error("count after persistent!");};g.ka=function(a,b){return this.H(null,b,null)};g.H=function(a,b,c){if(this.Wa)return a=yd(this.i,b),-1===a?c:this.i[a+1];throw Error("lookup after persistent!");};
g.$a=function(a,b){if(this.Wa){if(Ad(b))return this.Va(null,Nd.g?Nd.g(b):Nd.call(null,b),Od.g?Od.g(b):Od.call(null,b));if(ic(b))return this.Va(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));a=K(b);for(b=this;;){var c=N(a);if(v(c))a=P(a),b=eb(b,Nd.g?Nd.g(c):Nd.call(null,c),Od.g?Od.g(c):Od.call(null,c));else return b}}else throw Error("conj! after persistent!");};g.ib=function(){if(this.Wa)return this.Wa=!1,new ia(null,wc(this.Sa),this.i,null);throw Error("persistent! called twice");};
g.Va=function(a,b,c){if(this.Wa){a=yd(this.i,b);if(-1===a){if(this.Sa+2<=2*Gd)return this.Sa+=2,this.i.push(b),this.i.push(c),this;a=Pd.h?Pd.h(this.Sa,this.i):Pd.call(null,this.Sa,this.i);return eb(a,b,c)}c!==this.i[a+1]&&(this.i[a+1]=c);return this}throw Error("assoc! after persistent!");};g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};
g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.g=function(a){return this.H(null,a,null)};g.h=function(a,b){return this.H(null,a,b)};function Pd(a,b){for(var c=bb(Hd),d=0;;)if(d<a)c=eb(c,b[d],b[d+1]),d+=2;else return c}function Qd(){this.G=!1}function Rd(a,b,c){a=B(a);a[b]=c;return a}function Sd(a,b,c,d){a=a.Ra(b);a.i[c]=d;return a}
function Td(a,b,c){for(var d=a.length,e=0,f=c;;)if(e<d){c=a[e];if(null!=c){var h=a[e+1];c=b.l?b.l(f,c,h):b.call(null,f,c,h)}else c=a[e+1],c=null!=c?c.cb(b,f):f;if(Kb(c))return c;e+=2;f=c}else return f}function Ud(a){this.i=a;this.o=0;this.pa=this.eb=null}Ud.prototype.advance=function(){for(var a=this.i.length;;)if(this.o<a){var b=this.i[this.o],c=this.i[this.o+1];null!=b?b=this.eb=new zd(b,c):null!=c?(b=jb(c),b=b.ia()?this.pa=b:!1):b=!1;this.o+=2;if(b)return!0}else return!1};
Ud.prototype.ia=function(){var a=null!=this.eb;return a?a:(a=null!=this.pa)?a:this.advance()};Ud.prototype.next=function(){if(null!=this.eb){var a=this.eb;this.eb=null;return a}if(null!=this.pa)return a=this.pa.next(),this.pa.ia()||(this.pa=null),a;if(this.advance())return this.next();throw Error("No such element");};Ud.prototype.remove=function(){return Error("Unsupported operation")};function Vd(a,b,c){this.D=a;this.N=b;this.i=c;this.A=131072;this.j=0}g=Vd.prototype;
g.Ra=function(a){if(a===this.D)return this;var b=xc(this.N),c=Array(0>b?4:2*(b+1));kc(this.i,0,c,0,2*b);return new Vd(a,this.N,c)};g.bb=function(){return Wd?Wd(this.i):Xd.call(null,this.i)};g.cb=function(a,b){return Td(this.i,a,b)};g.za=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.N&e))return d;var f=xc(this.N&e-1);e=this.i[2*f];f=this.i[2*f+1];return null==e?f.za(a+5,b,c,d):Id(c,e)?f:d};
g.na=function(a,b,c,d,e,f){var h=1<<(c>>>b&31),k=xc(this.N&h-1);if(0===(this.N&h)){var l=xc(this.N);if(2*l<this.i.length){a=this.Ra(a);b=a.i;f.G=!0;c=2*(l-k);f=2*k+(c-1);for(l=2*(k+1)+(c-1);0!==c;)b[l]=b[f],--l,--c,--f;b[2*k]=d;b[2*k+1]=e;a.N|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Yd.na(a,b+5,c,d,e,f);for(e=d=0;;)if(32>d)0===(this.N>>>d&1)?
d+=1:(k[d]=null!=this.i[e]?Yd.na(a,b+5,ub(this.i[e]),this.i[e],this.i[e+1],f):this.i[e+1],e+=2,d+=1);else break;return new Zd(a,l+1,k)}b=Array(2*(l+4));kc(this.i,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;kc(this.i,2*k,b,2*(k+1),2*(l-k));f.G=!0;a=this.Ra(a);a.i=b;a.N|=h;return a}l=this.i[2*k];h=this.i[2*k+1];if(null==l)return l=h.na(a,b+5,c,d,e,f),l===h?this:Sd(this,a,2*k+1,l);if(Id(d,l))return e===h?this:Sd(this,a,2*k+1,e);f.G=!0;f=b+5;d=$d?$d(a,f,l,h,c,d,e):ae.call(null,a,f,l,h,c,d,e);e=2*k;k=2*k+1;a=this.Ra(a);
a.i[e]=null;a.i[k]=d;return a};
g.ma=function(a,b,c,d,e){var f=1<<(b>>>a&31),h=xc(this.N&f-1);if(0===(this.N&f)){var k=xc(this.N);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Yd.ma(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0===(this.N>>>c&1)?c+=1:(h[c]=null!=this.i[d]?Yd.ma(a+5,ub(this.i[d]),this.i[d],this.i[d+1],e):this.i[d+1],d+=2,c+=1);else break;return new Zd(null,k+1,h)}a=Array(2*(k+1));kc(this.i,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;kc(this.i,2*h,a,2*(h+1),2*(k-h));e.G=!0;return new Vd(null,this.N|f,a)}var l=this.i[2*h];f=this.i[2*h+1];if(null==l)return k=f.ma(a+5,b,c,d,e),k===f?this:new Vd(null,this.N,Rd(this.i,2*h+1,k));if(Id(c,l))return d===f?this:new Vd(null,this.N,Rd(this.i,2*h+1,d));e.G=!0;e=this.N;k=this.i;a+=5;a=be?be(a,l,f,b,c,d):ae.call(null,a,l,f,b,c,d);c=2*h;h=2*h+1;d=B(k);d[c]=null;d[h]=a;return new Vd(null,e,d)};g.sa=function(){return new Ud(this.i)};var Yd=new Vd(null,0,[]);
function ce(a){this.i=a;this.o=0;this.pa=null}ce.prototype.ia=function(){for(var a=this.i.length;;){if(null!=this.pa&&this.pa.ia())return!0;if(this.o<a){var b=this.i[this.o];this.o+=1;null!=b&&(this.pa=jb(b))}else return!1}};ce.prototype.next=function(){if(this.ia())return this.pa.next();throw Error("No such element");};ce.prototype.remove=function(){return Error("Unsupported operation")};function Zd(a,b,c){this.D=a;this.m=b;this.i=c;this.A=131072;this.j=0}g=Zd.prototype;
g.Ra=function(a){return a===this.D?this:new Zd(a,this.m,B(this.i))};g.bb=function(){return de?de(this.i):ee.call(null,this.i)};g.cb=function(a,b){for(var c=this.i.length,d=0;;)if(d<c){var e=this.i[d];if(null!=e){b=e.cb(a,b);if(Kb(b))return b;d+=1}else d+=1}else return b};g.za=function(a,b,c,d){var e=this.i[b>>>a&31];return null!=e?e.za(a+5,b,c,d):d};
g.na=function(a,b,c,d,e,f){var h=c>>>b&31,k=this.i[h];if(null==k)return a=Sd(this,a,h,Yd.na(a,b+5,c,d,e,f)),a.m+=1,a;b=k.na(a,b+5,c,d,e,f);return b===k?this:Sd(this,a,h,b)};g.ma=function(a,b,c,d,e){var f=b>>>a&31,h=this.i[f];if(null==h)return new Zd(null,this.m+1,Rd(this.i,f,Yd.ma(a+5,b,c,d,e)));a=h.ma(a+5,b,c,d,e);return a===h?this:new Zd(null,this.m,Rd(this.i,f,a))};g.sa=function(){return new ce(this.i)};function fe(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Id(c,a[d]))return d;d+=2}else return-1}
function ge(a,b,c,d){this.D=a;this.ya=b;this.m=c;this.i=d;this.A=131072;this.j=0}g=ge.prototype;g.Ra=function(a){if(a===this.D)return this;var b=Array(2*(this.m+1));kc(this.i,0,b,0,2*this.m);return new ge(a,this.ya,this.m,b)};g.bb=function(){return Wd?Wd(this.i):Xd.call(null,this.i)};g.cb=function(a,b){return Td(this.i,a,b)};g.za=function(a,b,c,d){a=fe(this.i,this.m,c);return 0>a?d:Id(c,this.i[a])?this.i[a+1]:d};
g.na=function(a,b,c,d,e,f){if(c===this.ya){b=fe(this.i,this.m,d);if(-1===b){if(this.i.length>2*this.m)return b=2*this.m,c=2*this.m+1,a=this.Ra(a),a.i[b]=d,a.i[c]=e,f.G=!0,a.m+=1,a;c=this.i.length;b=Array(c+2);kc(this.i,0,b,0,c);b[c]=d;b[c+1]=e;f.G=!0;d=this.m+1;a===this.D?(this.i=b,this.m=d,a=this):a=new ge(this.D,this.ya,d,b);return a}return this.i[b+1]===e?this:Sd(this,a,b+1,e)}return(new Vd(a,1<<(this.ya>>>b&31),[null,this,null,null])).na(a,b,c,d,e,f)};
g.ma=function(a,b,c,d,e){return b===this.ya?(a=fe(this.i,this.m,c),-1===a?(a=2*this.m,b=Array(a+2),kc(this.i,0,b,0,a),b[a]=c,b[a+1]=d,e.G=!0,new ge(null,this.ya,this.m+1,b)):R.h(this.i[a+1],d)?this:new ge(null,this.ya,this.m,Rd(this.i,a+1,d))):(new Vd(null,1<<(this.ya>>>a&31),[null,this])).ma(a,b,c,d,e)};g.sa=function(){return new Ud(this.i)};
function ae(a){switch(arguments.length){case 6:return be(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return $d(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function be(a,b,c,d,e,f){var h=ub(b);if(h===d)return new ge(null,h,2,[b,c,e,f]);var k=new Qd;return Yd.ma(a,h,b,c,k).ma(a,d,e,f,k)}
function $d(a,b,c,d,e,f,h){var k=ub(c);if(k===e)return new ge(null,k,2,[c,d,f,h]);var l=new Qd;return Yd.na(a,b,k,c,d,l).na(a,b,e,f,h,l)}function he(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.C=d;this.v=e;this.j=32374988;this.A=0}g=he.prototype;g.toString=function(){return lb(this)};
g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){if(null==this.C){var a=this.qa,b=this.o+2;return ie?ie(a,b,null):Xd.call(null,a,b,null)}a=this.qa;b=this.o;var c=P(this.C);return ie?ie(a,b,c):Xd.call(null,a,b,c)};
g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};g.W=function(){return O};g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return null==this.C?new zd(this.qa[this.o],this.qa[this.o+1]):N(this.C)};
g.ga=function(){var a=this,b=null==a.C?function(){var c=a.qa,d=a.o+2;return ie?ie(c,d,null):Xd.call(null,c,d,null)}():function(){var c=a.qa,d=a.o,e=P(a.C);return ie?ie(c,d,e):Xd.call(null,c,d,e)}();return null!=b?b:O};g.I=function(){return this};g.R=function(a,b){return b===this.u?this:new he(b,this.qa,this.o,this.C,this.v)};g.U=function(a,b){return V(b,this)};he.prototype[qa]=function(){return Db(this)};
function Xd(a){switch(arguments.length){case 1:return Wd(arguments[0]);case 3:return ie(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function Wd(a){return ie(a,0,null)}function ie(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new he(null,a,b,null,null);var d=a[b+1];if(v(d)&&(d=d.bb(),v(d)))return new he(null,a,b+2,d,null);b+=2}else return null;else return new he(null,a,b,c,null)}
function je(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.C=d;this.v=e;this.j=32374988;this.A=0}g=je.prototype;g.toString=function(){return lb(this)};g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.u};g.Z=function(){var a=this.qa,b=this.o,c=P(this.C);return ke?ke(a,b,c):ee.call(null,a,b,c)};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};g.K=function(a,b){return Ub(this,b)};
g.W=function(){return O};g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return N(this.C)};g.ga=function(){var a=this.qa;var b=this.o,c=P(this.C);a=ke?ke(a,b,c):ee.call(null,a,b,c);return null!=a?a:O};g.I=function(){return this};g.R=function(a,b){return b===this.u?this:new je(b,this.qa,this.o,this.C,this.v)};g.U=function(a,b){return V(b,this)};je.prototype[qa]=function(){return Db(this)};
function ee(a){switch(arguments.length){case 1:return de(arguments[0]);case 3:return ke(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function de(a){return ke(a,0,null)}function ke(a,b,c){if(null==c)for(c=a.length;;)if(b<c){var d=a[b];if(v(d)&&(d=d.bb(),v(d)))return new je(null,a,b+1,d,null);b+=1}else return null;else return new je(null,a,b,c,null)}function le(a,b){this.da=a;this.wb=b;this.pb=!1}
le.prototype.ia=function(){return!this.pb||this.wb.ia()};le.prototype.next=function(){if(this.pb)return this.wb.next();this.pb=!0;return new zd(null,this.da)};le.prototype.remove=function(){return Error("Unsupported operation")};function me(a,b,c,d,e,f){this.u=a;this.m=b;this.root=c;this.ha=d;this.da=e;this.v=f;this.j=16123663;this.A=139268}g=me.prototype;g.toString=function(){return lb(this)};g.keys=function(){return Db(Dd.g?Dd.g(this):Dd.call(null,this))};g.entries=function(){return new xd(K(K(this)))};
g.values=function(){return Db(Ed.g?Ed.g(this):Ed.call(null,this))};g.has=function(a){return nc(this,a)};g.get=function(a,b){return this.H(null,a,b)};g.forEach=function(a){for(var b=K(this),c=null,d=0,e=0;;)if(e<d){var f=c.T(null,e),h=W(f,0,null);f=W(f,1,null);a.h?a.h(f,h):a.call(null,f,h);e+=1}else if(b=K(b))jc(b)?(c=gb(b),b=hb(b),h=c,d=T(c),c=h):(c=N(b),h=W(c,0,null),f=W(c,1,null),a.h?a.h(f,h):a.call(null,f,h),b=P(b),c=null,d=0),e=0;else return null};g.ka=function(a,b){return this.H(null,b,null)};
g.H=function(a,b,c){return null==b?this.ha?this.da:c:null==this.root?c:this.root.za(0,ub(b),b,c)};g.hb=function(a,b,c){a=this.ha?b.l?b.l(c,null,this.da):b.call(null,c,null,this.da):c;Kb(a)?b=Ka(a):null!=this.root?(b=this.root.cb(b,a),b=Kb(b)?Lb.g?Lb.g(b):Lb.call(null,b):b):b=a;return b};g.sa=function(){var a=this.root?jb(this.root):new Wc(Vc);return this.ha?new le(this.da,a):a};g.P=function(){return this.u};g.V=function(){return this.m};g.O=function(){var a=this.v;return null!=a?a:this.v=a=Hb(this)};
g.K=function(a,b){return wd(this,b)};g.Xa=function(){return new ne(this.root,this.m,this.ha,this.da)};g.W=function(){return Na(Hd,this.u)};g.xa=function(a,b,c){if(null==b)return this.ha&&c===this.da?this:new me(this.u,this.ha?this.m:this.m+1,this.root,!0,c,null);a=new Qd;b=(null==this.root?Yd:this.root).ma(0,ub(b),b,c,a);return b===this.root?this:new me(this.u,a.G?this.m+1:this.m,b,this.ha,this.da,null)};g.Ua=function(a,b){return null==b?this.ha:null==this.root?!1:this.root.za(0,ub(b),b,lc)!==lc};
g.I=function(){if(0<this.m){var a=null!=this.root?this.root.bb():null;return this.ha?V(new zd(null,this.da),a):a}return null};g.R=function(a,b){return b===this.u?this:new me(b,this.m,this.root,this.ha,this.da,this.v)};g.U=function(a,b){if(ic(b))return this.xa(null,D(b,0),D(b,1));a=this;for(b=K(b);;){if(null==b)return a;var c=N(b);if(ic(c))a=Fa(a,D(c,0),D(c,1)),b=P(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};g.g=function(a){return this.ka(null,a)};g.h=function(a,b){return this.H(null,a,b)};var Hd=new me(null,0,null,!1,null,Ib);me.prototype[qa]=function(){return Db(this)};
function ne(a,b,c,d){this.D={};this.root=a;this.count=b;this.ha=c;this.da=d;this.j=259;this.A=56}function oe(a,b,c){if(a.D){if(null==b)a.da!==c&&(a.da=c),a.ha||(a.count+=1,a.ha=!0);else{var d=new Qd;b=(null==a.root?Yd:a.root).na(a.D,0,ub(b),b,c,d);b!==a.root&&(a.root=b);d.G&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}g=ne.prototype;g.V=function(){if(this.D)return this.count;throw Error("count after persistent!");};
g.ka=function(a,b){return null==b?this.ha?this.da:null:null==this.root?null:this.root.za(0,ub(b),b)};g.H=function(a,b,c){return null==b?this.ha?this.da:c:null==this.root?c:this.root.za(0,ub(b),b,c)};
g.$a=function(a,b){a:if(this.D)if(Ad(b))a=oe(this,Nd.g?Nd.g(b):Nd.call(null,b),Od.g?Od.g(b):Od.call(null,b));else if(ic(b))a=oe(this,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));else for(a=K(b),b=this;;){var c=N(a);if(v(c))a=P(a),b=oe(b,Nd.g?Nd.g(c):Nd.call(null,c),Od.g?Od.g(c):Od.call(null,c));else{a=b;break a}}else throw Error("conj! after persistent");return a};
g.ib=function(){if(this.D){this.D=null;var a=new me(null,this.count,this.root,this.ha,this.da,null)}else throw Error("persistent! called twice");return a};g.Va=function(a,b,c){return oe(this,b,c)};g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};g.apply=function(a,b){return this.call.apply(this,[this].concat(B(b)))};
g.g=function(a){return this.ka(null,a)};g.h=function(a,b){return this.H(null,a,b)};function pe(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0}g=pe.prototype;g.toString=function(){return lb(this)};g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.ra};g.Z=function(){var a=(null!=this.B?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(za,this.B)):w(za,this.B))?this.B.Z():P(this.B);return null==a?null:new pe(a,null)};g.O=function(){return Fb(this)};
g.K=function(a,b){return Ub(this,b)};g.W=function(){return O};g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return this.B.ca(null).key};g.ga=function(){var a=(null!=this.B?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(za,this.B)):w(za,this.B))?this.B.Z():P(this.B);return null!=a?new pe(a,null):O};g.I=function(){return this};g.R=function(a,b){return b===this.ra?this:new pe(this.B,b)};g.U=function(a,b){return V(b,this)};pe.prototype[qa]=function(){return Db(this)};
function Dd(a){return(a=K(a))?new pe(a,null):null}function Nd(a){return Ha(a)}function qe(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0}g=qe.prototype;g.toString=function(){return lb(this)};g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return S(this,b,0);case 2:return S(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return S(this,b,0)};a.h=function(b,c){return S(this,b,c)};return a}();
g.lastIndexOf=function(){function a(c){return U(this,c,T(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return U(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return U(this,c,d)};return b}();g.P=function(){return this.ra};g.Z=function(){var a=(null!=this.B?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(za,this.B)):w(za,this.B))?this.B.Z():P(this.B);return null==a?null:new qe(a,null)};g.O=function(){return Fb(this)};
g.K=function(a,b){return Ub(this,b)};g.W=function(){return O};g.aa=function(a,b){return oc(b,this)};g.ba=function(a,b,c){return rc(b,c,this)};g.ca=function(){return this.B.ca(null).G};g.ga=function(){var a=(null!=this.B?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(za,this.B)):w(za,this.B))?this.B.Z():P(this.B);return null!=a?new qe(a,null):O};g.I=function(){return this};g.R=function(a,b){return b===this.ra?this:new qe(this.B,b)};g.U=function(a,b){return V(b,this)};qe.prototype[qa]=function(){return Db(this)};
function Ed(a){return(a=K(a))?new qe(a,null):null}function Od(a){return Ia(a)}function Cc(a){if(null!=a&&(a.A&4096||u===a.Ib))return a.name;if("string"===typeof a)return a;throw Error(["Doesn't support name: ",z.g(a)].join(""));}
function re(a,b,c,d,e,f,h){var k=fa;fa=null==fa?null:fa-1;try{if(null!=fa&&0>fa)return H(a,"#");H(a,c);if(0===oa.g(f))K(h)&&H(a,function(){var t=se.g(f);return v(t)?t:"..."}());else{if(K(h)){var l=N(h);b.l?b.l(l,a,f):b.call(null,l,a,f)}for(var m=P(h),n=oa.g(f)-1;;)if(!m||null!=n&&0===n){K(m)&&0===n&&(H(a,d),H(a,function(){var t=se.g(f);return v(t)?t:"..."}()));break}else{H(a,d);var p=N(m);c=a;h=f;b.l?b.l(p,c,h):b.call(null,p,c,h);var q=P(m);c=n-1;m=q;n=c}}return H(a,e)}finally{fa=k}}
function te(a,b){b=K(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.T(null,e);H(a,f);e+=1}else if(b=K(b))c=b,jc(c)?(b=gb(c),d=hb(c),c=b,f=T(b),b=d,d=f):(f=N(c),H(a,f),b=P(c),c=null,d=0),e=0;else return null}var ue={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function ve(a){return['"',z.g(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(b){return ue[b]})),'"'].join("")}
function we(a,b){return(a=mc(xb.h(a,la)))?(a=null!=b?b.j&131072||u===b.Hb?!0:!1:!1)?null!=ec(b):a:a}
function xe(a,b,c){if(null==a)return H(b,"nil");if(we(c,a)){H(b,"^");var d=ec(a);Z.l?Z.l(d,b,c):Z.call(null,d,b,c);H(b," ")}if(a.Mb)return a.ac(a,b,c);if(null!=a?a.j&2147483648||u===a.$||(a.j?0:w($a,a)):w($a,a))return ab(a,b,c);if(!0===a||!1===a)return H(b,z.g(a));if("number"===typeof a)return H(b,isNaN(a)?"##NaN":a===Number.POSITIVE_INFINITY?"##Inf":a===Number.NEGATIVE_INFINITY?"##-Inf":z.g(a));if(null!=a&&a.constructor===Object)return H(b,"#js "),d=X.h(function(f){var h=/[A-Za-z_\*\+\?!\-'][\w\*\+\?!\-']*/;
if("string"===typeof f)if(h=h.exec(f),null!=h&&R.h(h[0],f))if(1===h.length)h=h[0];else if(v(Ad.g?Ad.g(h):Ad.call(null,h)))h=new Y(null,2,5,od,[Nd.g?Nd.g(h):Nd.call(null,h),Od.g?Od.g(h):Od.call(null,h)],null);else if(ic(h))h=dc(h,null);else if(Array.isArray(h))b:{var k=h.length;if(32>k)h=new Y(null,k,5,od,h,null);else for(var l=32,m=(new Y(null,32,5,od,h.slice(0,32),null)).Xa(null);;)if(l<k){var n=l+1;m=cb(m,h[l]);l=n}else{h=db(m);break b}}else h=db(pc(cb,bb(Xb),h));else h=null;else throw new TypeError("re-matches must match against a string.");
return new zd(null!=h?Bc.g(f):f,a[f])},ca(a)),ye.fa?ye.fa(d,Z,b,c):ye.call(null,d,Z,b,c);if(Array.isArray(a))return re(b,Z,"#js ["," ","]",c,a);if("string"===typeof a)return v(ka.g(c))?H(b,ve(a)):H(b,a);if("function"===typeof a){var e=a.name;c=v(function(){var f=null==e;return f?f:/^[\s\xa0]*$/.test(e)}())?"Function":e;return te(b,Vb(["#object[",c,v(!1)?[' "',z.g(a),'"'].join(""):"","]"]))}if(a instanceof Date)return c=function(f,h){for(f=z.g(f);;)if(f.length<h)f=["0",f].join("");else return f},te(b,
Vb(['#inst "',c(a.getUTCFullYear(),4),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),"-",'00:00"']));if(a instanceof RegExp)return te(b,Vb(['#"',a.source,'"']));if("symbol"===r(a)||"undefined"!==typeof Symbol&&a instanceof Symbol)return te(b,Vb(["#object[",a.toString(),"]"]));if(v(function(){var f=null==a?null:a.constructor;return null==f?null:f.ob}()))return te(b,Vb(["#object[",a.constructor.ob.replace(RegExp("/",
"g"),"."),"]"]));e=function(){var f=null==a?null:a.constructor;return null==f?null:f.name}();c=v(function(){var f=null==e;return f?f:/^[\s\xa0]*$/.test(e)}())?"Object":e;return null==a.constructor?te(b,Vb(["#object[",c,"]"])):te(b,Vb(["#object[",c," ",z.g(a),"]"]))}function Z(a,b,c){var d=ze.g(c);return v(d)?(c=$b.l(c,Ae,xe),d.l?d.l(a,b,c):d.call(null,a,b,c)):xe(a,b,c)}function Be(a){return a instanceof wb?yb.h(null,Cc(a)):Bc.h(null,Cc(a))}
function Ce(a){if(v(!1)){var b=K(a),c=K(b),d=N(c);P(c);W(d,0,null);W(d,1,null);c=null==a?null:null!=a&&(a.j&4||u===a.Ab)?a.W(null):(null!=a?a.j&4||u===a.Ab||(a.j?0:w(ta,a)):w(ta,a))?ua(a):null;for(a=null;;){d=a;b=K(b);a=N(b);var e=P(b),f=a;a=W(f,0,null);b=W(f,1,null);if(v(f))if(a instanceof I||a instanceof wb)if(v(d))if(R.h(d,Ac(a)))c=$b.l(c,Be(a),b),a=d,b=e;else return null;else if(d=Ac(a),v(d))c=$b.l(c,Be(a),b),a=d,b=e;else return null;else return null;else return new Y(null,2,5,od,[d,c],null)}}else return null}
function De(a,b,c,d,e){return re(d,function(f,h,k){var l=Ha(f);c.l?c.l(l,h,k):c.call(null,l,h,k);H(h," ");f=Ia(f);return c.l?c.l(f,h,k):c.call(null,f,h,k)},[z.g(a),"{"].join(""),", ","}",e,K(b))}function ye(a,b,c,d){var e=gc(a)?Ce(a):null,f=W(e,0,null);e=W(e,1,null);return v(f)?De(["#:",z.g(f)].join(""),e,b,c,d):De(null,a,b,c,d)}M.prototype.$=u;M.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};Dc.prototype.$=u;Dc.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};
zd.prototype.$=u;zd.prototype.M=function(a,b,c){return re(b,Z,"["," ","]",c,this)};he.prototype.$=u;he.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};Bd.prototype.$=u;Bd.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};Eb.prototype.$=u;Eb.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};pd.prototype.$=u;pd.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};zc.prototype.$=u;zc.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};
me.prototype.$=u;me.prototype.M=function(a,b,c){return ye(this,Z,b,c)};je.prototype.$=u;je.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};Hc.prototype.$=u;Hc.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};qe.prototype.$=u;qe.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};Y.prototype.$=u;Y.prototype.M=function(a,b,c){return re(b,Z,"["," ","]",c,this)};yc.prototype.$=u;yc.prototype.M=function(a,b){return H(b,"()")};ia.prototype.$=u;
ia.prototype.M=function(a,b,c){return ye(this,Z,b,c)};pe.prototype.$=u;pe.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};Yb.prototype.$=u;Yb.prototype.M=function(a,b,c){return re(b,Z,"("," ",")",c,this)};function Ee(){}function Fe(a){if(null!=a&&null!=a.Cb)a=a.Cb(a);else{var b=Fe[r(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Fe._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IEncodeJS.-clj-\x3ejs",a);}return a}
function Ge(a,b){if(null!=a?u===a.Bb||(a.Lb?0:w(Ee,a)):w(Ee,a))a=Fe(a);else if("string"===typeof a||"number"===typeof a||a instanceof I||a instanceof wb)a=b.g?b.g(a):b.call(null,a);else{var c=Vb([a]);a=ha();(b=null==c)||(b=K(c),b=null==b?!0:!1===b?!0:!1);if(b)a="";else{b=z;var d=b.g,e=new da,f=new kb(e);Z(N(c),f,a);c=K(P(c));for(var h=null,k=0,l=0;;)if(l<k){var m=h.T(null,l);H(f," ");Z(m,f,a);l+=1}else if(c=K(c))h=c,jc(h)?(c=gb(h),k=hb(h),h=c,m=T(c),c=k,k=m):(m=N(h),H(f," "),Z(m,f,a),c=P(h),h=null,
k=0),l=0;else break;a=d.call(b,e)}}return a}var He=function He(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return He.J(arguments[0],1<c.length?new M(c.slice(1),0,null):null)};
He.J=function(a,b){b=Uc(b);var c=xb.l(b,Ie,Cc),d=function h(f){if(null==f)return null;if(null!=f?u===f.Bb||(f.Lb?0:w(Ee,f)):w(Ee,f))return Fe(f);if(f instanceof I)return c.g?c.g(f):c.call(null,f);if(f instanceof wb)return z.g(f);if(gc(f)){var k={};f=K(f);for(var l=null,m=0,n=0;;)if(n<m){var p=l.T(null,n),q=W(p,0,null);p=W(p,1,null);q=Ge(q,d);p=h(p);k[q]=p;n+=1}else if(f=K(f))jc(f)?(m=gb(f),f=hb(f),l=m,m=T(m)):(m=N(f),l=W(m,0,null),m=W(m,1,null),l=Ge(l,d),m=h(m),k[l]=m,f=P(f),l=null,m=0),n=0;else break;
return k}if(null==f?0:null!=f?f.j&8||u===f.Rb||(f.j?0:w(va,f)):w(va,f)){k=[];f=K(X.h(h,f));l=null;for(n=m=0;;)if(n<m)q=l.T(null,n),k.push(q),n+=1;else if(f=K(f))l=f,jc(l)?(f=gb(l),n=hb(l),l=f,m=T(f),f=n):(f=N(l),k.push(f),f=P(l),l=null,m=0),n=0;else break;return k}return f};return d(a)};He.Y=1;He.X=function(a){var b=N(a);a=P(a);return this.J(b,a)};var la=new I(null,"meta","meta",1499536964),oa=new I(null,"print-length","print-length",1931866356),ja=new I(null,"flush-on-newline","flush-on-newline",-151457939),na=new I(null,"dup","dup",556298533),ka=new I(null,"readably","readably",1129599760),Ae=new I(null,"fallback-impl","fallback-impl",-1501286995),Ie=new I(null,"keyword-fn","keyword-fn",-64566675),se=new I(null,"more-marker","more-marker",-14717935),ze=new I(null,"alt-impl","alt-impl",670969595);function Je(a){return v(a)?nova.openURL(a,function(){return null}):null};shadow$umd$export=function(){return nova.commands.register("clojure-test.openURL",function(){var a=He(new ia(null,2,["placeholder","https://foobar.com","prompt","Open"],null));return nova.workspace.showInputPanel("Enter the URL to open:",a,Je)})};return shadow$umd$export;
});